version: "3.9"
services:
  k0s-master:
    container_name: k0s
    image: docker.io/zengzhengrong889/k0s:bullseye-nvidia
    entrypoint: ["sh","entrypoint.sh"]
    hostname: k0s
    privileged: true
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
      - "./certs.d:/etc/containerd/certs.d"
      - "/var/lib/k0s"
      - "./config.yaml:/etc/k0s/config.yaml"
      - "./admin.conf:/var/lib/k0s/pki/admin.conf"
      - "./airgap/localtime:/etc/localtime"
      - "./token:/var/token"
    tmpfs:
      - /run
      - /var/run
    ports:
      - "6443:6443"
      - "80:32080"
      - "443:32443"
      - "3306:30306"
      - "6650:30665"
      - "6379:30379"
    network_mode: "bridge"
  k0s-worker1: &k0s-worker
    container_name: k0s-worker1
    image: docker.io/zengzhengrong889/k0s:bullseye-nvidia
    entrypoint: ["sh","entrypoint-worker.sh","/var/token/k0s.token"]
    hostname: k0s-worker1
    privileged: true
    volumes:
      - "./entrypoint-worker.sh:/entrypoint-worker.sh"
      - "./certs.d:/etc/containerd/certs.d"
      - "/var/lib/k0s"
      - "./data:/var/openebs"
      - "./airgap/localtime:/etc/localtime"
      - "./token:/var/token"
    network_mode: "bridge"
  k0s-worker2:
    <<: *k0s-worker
    container_name: k0s-worker2
    hostname: k0s-worker2
  # k0s-worker3:
  #   <<: *k0s-worker
  #   container_name: k0s-worker3
  #   hostname: k0s-worker3
