version: "3.9"
services:
  k0s-master:
    container_name: k0s
    image: docker.io/k0sproject/k0s:v1.23.10-k0s.0
    entrypoint: ["sh","entrypoint.sh"]
    hostname: k0s
    privileged: true
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
      - "./certs.d:/etc/containerd/certs.d"
      - "/var/lib/k0s"
      - "./config.yaml:/etc/k0s/config.yaml"
      - "./containerd.toml:/etc/k0s/containerd.toml"
      - "./admin.conf:/var/lib/k0s/pki/admin.conf"
      - "./airgap/localtime:/etc/localtime"
      - "./token:/var/token"
    tmpfs:
      - /run
      - /var/run
    ports:
      - "6443:6443"
      - "80:32080"
      - "443:32443"
      - "3306:30306"
      - "8080:8080"
      - "8000:8000"
      - "6650:30665"
    network_mode: "bridge"
    environment:
      - HTTP_PROXY=http://192.168.2.102:7890
  k0s-worker1: &k0s-worker
    container_name: k0s-worker1
    image: docker.io/k0sproject/k0s:v1.23.10-k0s.0
    entrypoint: ["sh","entrypoint-worker.sh","/var/token/k0s.token"]
    hostname: k0s-worker1
    privileged: true
    volumes:
      - "./entrypoint-worker.sh:/entrypoint-worker.sh"
      - "./certs.d:/etc/containerd/certs.d"
      - "/var/lib/k0s"
      - "./data:/var/openebs"
      # - "./airgap/bundle/bundle_file:/var/lib/k0s/images/bundle_file"
      - "./containerd.toml:/etc/k0s/containerd.toml"
      - "./airgap/localtime:/etc/localtime"
      - "./token:/var/token"
    network_mode: "bridge"
    environment:
      - HTTP_PROXY=http://192.168.2.102:7890
  k0s-worker2:
    <<: *k0s-worker
    container_name: k0s-worker2
    hostname: k0s-worker2
  # k0s-worker3:
  #   <<: *k0s-worker
  #   container_name: k0s-worker3
  #   hostname: k0s-worker3
