version: "3.9"
services:
  k0s:
    container_name: k0s
    image: docker.io/zengzhengrong889/k0s:bullseye-nvidia
    command: k0s controller --config=/etc/k0s/config.yaml --single
    hostname: k0s
    privileged: true
    runtime: nvidia
    volumes:
      - "/var/lib/k0s"
      - "./config.yaml:/etc/k0s/config.yaml"
      - "./admin.conf:/var/lib/k0s/pki/admin.conf"
      - "./data:/var/openebs"
      - "./airgap/bundle_file:/var/lib/k0s/images/bundle_file"
      - "./airgap/localtime:/etc/localtime"
    tmpfs:
      - /run
      - /var/run
    ports:
      - "6443:6443"
      - "80:32080"
      - "443:32443"
      - "3306:30306"
      - "8080:8080"
      - "8000:8000"
    network_mode: "bridge"
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: "all"
              capabilities: ["gpu"]