# https://github.com/mongodb/mongodb-kubernetes-operator#documentation
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
  namespace: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  # https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/users.md
  users:
    - name: zzr
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: example-mongodb-zzr-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: example-mongodb-zzr-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

  statefulSet:
    spec:
        # Name for the service object created by the operator
      serviceName: example-mongodb-svc
      selector: {}
        # Specifies a size for the data volume different from the default 10Gi
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: 
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: openebs-hostpath
        - metadata:
            name: logs-volume
          spec:
            accessModes: 
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: openebs-hostpath
            

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: example-mongodb-zzr-password
  namespace: mongodb
type: Opaque
stringData:
  password: admin