apiVersion: v1
kind: Pod
metadata:
   name: dcgmproftester
spec:
   restartPolicy: OnFailure
   containers:
   - name: dcgmproftester11
     image: docker.io/zengzhengrong889/nvidia-samples:dcgmproftester-2.0.10-cuda11.0-ubuntu18.04
     args: ["--no-dcgm-validation", "-t 1004", "-d 30"]
     resources:
       limits:
        nvidia.com/gpu: "0"
        cpu: "1"
        memory: 100Mi
     securityContext:
       privileged: true
       capabilities:
         add: ["SYS_ADMIN"]