apiVersion: v1
kind: Pod
metadata:
  name: cuda-vectoradd
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-vectoradd
    image: "nvidia/samples:vectoradd-cuda11.6.0-ubuntu20.04"
    resources:
      limits:
        nvidia.com/gpu: "0"
        cpu: "1"
        memory: 100Mi