# https://discuss.elastic.co/t/dont-want-to-use-https-and-user-password/202332/8
# https://discuss.elastic.co/t/fatal-error-config-validation-of-xpack-security-enabled-definition-for-this-key-is-missing/300396
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: noauth
  namespace: eck-stack
spec:
  count: 1
  elasticsearchRef:
    name: noauth
  version: 8.4.3
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5601
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2.5Gi
            cpu: 1
