apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: argocd-extension-metrics
spec:
  project: default
  source:
    repoURL: 'https://github.com/zengzhengrong/argocd-extension-metrics.git'
    path: manifests
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

