apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-workflows
    helm:
      parameters:
      - name: server.ingress.enabled
        value: "true"
      - name: server.ingress.ingressClassName
        value: nginx
      - name: mainContainer.imagePullPolicy
        value: IfNotPresent
      - name: images.pullPolicy
        value: IfNotPresent
      - name: server.servicePortName
        value: http
      - name: server.ingress.hosts[0]
        value: argostack.localhost
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.30.0
  syncPolicy:
    automated:
      prune: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true