# https://github.com/elastic/cloud-on-k8s/tree/2.4/deploy/eck-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: eck-operator
spec:
  project: default
  source:
    repoURL: 'https://helm.elastic.co'
    targetRevision: 2.4.0
    chart: eck-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elastic-system
  syncPolicy: 
    syncOptions:
      - CreateNamespace=true