apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: eck-stack-noauth
spec:
  project: default
  source:
    repoURL: 'https://github.com/zengzhengrong/k0s-stack'
    path: docs/eck/no_auth
    targetRevision: zh-cn
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: eck-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
