apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    helm:
      parameters:
      # zh-cn uncomment this
      # - name: controller.admissionWebhooks.patch.image.image
      #   value: google_containers/kube-webhook-certgen
      # - name: controller.admissionWebhooks.patch.image.digest
      #   value: sha256:64d8c73dca984af206adf9d6d7e46aa550362b1d7a01f3a0a91b20cc67868660
      # - name: controller.admissionWebhooks.patch.image.registry
      #   value: registry.aliyuncs.com
      # - name: controller.image.image
      #   value: google_containers/nginx-ingress-controller
      # - name: controller.image.registry
      #   value: registry.aliyuncs.com
      - name: controller.tolerations[0].key
        value: node-role.kubernetes.io/master
      - name: controller.tolerations[0].operator
        value: Exists
      - name: controller.tolerations[0].effect
        value: NoSchedule
      - name: controller.nodeSelector.\node\.k0sproject\.io/role
        value: control-plane
      - name: controller.service.type
        value: NodePort
      - name: controller.service.nodePorts.http
        value: '32080'
      - name: controller.service.nodePorts.https
        value: '32443'
      - name: controller.service.nodePorts.tcp.6550
        value: '30665'
      - name: controller.service.nodePorts.tcp.6379
        value: '30379'
      - name: controller.service.nodePorts.tcp.3306
        value: '30306'
      - name: controller.service.nodePorts.tcp.9000
        value: '30900'
      - name: controller.service.nodePorts.tcp.8123
        value: '30812'
      - name: tcp.6550
        value: 'pulsar/pulsar-proxy:6650'
      - name: tcp.3306
        value: 'radondb-mysql/sample-leader:3306'
      - name: tcp.6379
        value: 'redis/redis-standalone-external-service:6379'
      - name: tcp.9000
        value: 'clickhouse/clickhouse-minimal:9000'
      - name: tpc.8123
        value: 'clickhouse/clickhouse-minimal:8123'
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.2.3
  syncPolicy:
    automated:
      prune: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true