apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
spec:
  project: default
  source:
    repoURL: 'https://openebs.github.io/charts'
    targetRevision: 3.3.1
    helm:
      parameters:
        - name: localpv-provisioner.enabled
          value: 'true'
        - name: ndm.enabled
          value: 'false'
        - name: provisioner.enabled
          value: 'false'
        - name: ndmOperator.enabled
          value: 'false'
    chart: openebs
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
