apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.1.3
    helm:
      parameters:
        - name: global.storageClass
          value: openebs-hostpath
    chart: postgresql
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgresql
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  info:
    - name: link
      value: https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
    - name: user
      value: postgres 
    - name: password
      value: kubectl get secrets/postgresql -n postgresql -oyaml
