apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: pulsar
spec:
  project: default
  source:
    repoURL: 'https://pulsar.apache.org/charts'
    targetRevision: 2.9.4
    helm:
      parameters:
        - name: images.pulsar_manager.tag
          value: 'v0.2.0'
        - name: volumes.persistence
          value: 'false'
        - name: broker.affinity.anti_affinity
          value: 'false'
        - name: components.pulsar_manager
          value: 'true'
        - name: pulsar_manager.service.type
          value: 'ClusterIP'
        - name: pulsar_manager.ingress.enabled
          value: 'true'
        - name: pulsar_manager.ingress.hostname
          value: 'pulsarmanager.localhost'
        - name: pulsar_manager.ingress.annotations.kubernetes\.io/ingress\.class
          value: nginx
        - name: pulsar_manager.restartPodsOnConfigMapChange
          value: 'false'
        - name: proxy.service.type
          value: 'ClusterIP'
        - name: proxy.ingress.enabled
          value: 'true'
        - name: proxy.ingress.annotations.kubernetes\.io/ingress\.class
          value: nginx
        - name: proxy.ingress.hostname
          value: 'pulsarproxy.localhost'
        - name: components.autorecovery
          value: 'true'
        - name: zookeeper.replicaCount
          value: '1'
        - name: bookkeeper.replicaCount
          value: '1'
        - name: broker.replicaCount
          value: '1'
        - name: proxy.replicaCount
          value: '1'
        - name: broker.configData.managedLedgerDefaultAckQuorum
          value: '1'
          forceString: true
        - name: broker.configData.managedLedgerDefaultEnsembleSize
          value: '1'
          forceString: true
        - name: broker.configData.managedLedgerDefaultWriteQuorum
          value: '1'
          forceString: true
        - name: broker.configData.autoSkipNonRecoverableData
          value: 'true'
          forceString: true
        - name: monitoring.alert_manager
          value: 'false'
        - name: monitoring.prometheus
          value: 'false'
        - name: monitoring.node_exporter
          value: 'false'
        - name: monitoring.grafana
          value: 'false'
        - name: kube-prometheus-stack.enabled
          value: 'false'
    chart: pulsar
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pulsar
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
