apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator
spec:
  project: default
  source:
    repoURL: 'https://ot-container-kit.github.io/helm-charts/'
    targetRevision: 0.12.0
    chart: redis-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redis
  syncPolicy:
    syncOptions:
      - CreateNamespace=true


