apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: sealed-secrets
spec:
  project: default
  source:
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: 2.7.3
    helm:
      parameters:
        - name: fullnameOverride
          value: sealed-secrets-controller
        - name: ingress.enabled
          value: 'true'
        - name: ingress.hostname
          value: sealed-secrets.localhost
        - name: ingress.ingressClassName
          value: nginx
    chart: sealed-secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  info:
    - name: link
      value: https://github.com/bitnami-labs/sealed-secrets#controller

