apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: zookeeper
spec:
  project: default
  source:
    repoURL: 'https://zengzhengrong.github.io/helm-charts'
    targetRevision: 3.7.1
    helm:
      parameters:
        - name: image.repository
          value: hypertrace/zookeeper
        - name: image.tagOverride
          value: latest
    chart: zookeeper
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: zookeeper
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
