apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openim-logs
  namespace: openim
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
