apiVersion: v1
kind: ConfigMap
metadata:
  name: openim-usual-config
  namespace: openim
  labels:
    app: openim
data:
  usualConfig.yaml: |
    # etcd: 
    # userName: root
    # password: LLaeWDvYUT
    # secret:

    mysql:
      dbMysqlUserName: root #mysql用户名
      dbMysqlPassword: root # mysql密码

    mongo:
      dbUserName:  #mongo用户名
      dbPassword:  #mongo密码

    redis:
      dbUserName:
      dbPassWord: #redis密码

    kafka:
      SASLUserName:
      SASLPassword:

    credential:
      minio:
        endpoint: http://127.0.0.1:10005 #发图片视频文件需要填写
        accessKeyID: root
        secretAccessKey: openIM123


    tokenpolicy:
      accessSecret: "open_im_server" #token生成相关 建议修改
      accessExpire: 90 #token过期时间（天） 默认即可

    messageverify:
      friendVerify: false #发送消息是否验证好友关系 false表示不验证好友关系

    push:
      getui:
        pushUrl: "https://restapi.getui.com/v2/$appId"
        masterSecret: ""  #需添加
        appKey: ""  #需添加
        enable: false  #true启动个推推送