---
apiVersion: v1
kind: Secret
metadata:
  # Corresponding to the user's secretName
  name: sample-user-password
  namespace: radondb
data:
  # The key corresponding to the user's secretKey
  # RadonDB@123
  superUser: UmFkb25EQkAxMjM=
  normalUser: UmFkb25EQkAxMjM=
---
apiVersion: mysql.radondb.com/v1alpha1
kind: MysqlUser
metadata:
  name: super-user
  namespace: radondb
spec:
  ## MySQL user name.
  user: super_user
  withGrantOption: true
  tlsOptions: 
    type: NONE
  hosts: 
    - "%"
  permissions:
    - database: "*"
      tables:
        - "*"
      privileges:
        - ALL
  ## Specify the cluster where the user is located.
  userOwner:
    clusterName: sample
    nameSpace: radondb
  ## Specify the secret object for user.
  secretSelector:
    secretName: sample-user-password
    secretKey: superUser
---
apiVersion: mysql.radondb.com/v1alpha1
kind: MysqlUser
metadata:
  name: normal-user
  namespace: radondb
spec:
  ## MySQL user name.
  user: normal_user
  withGrantOption: false
  tlsOptions: 
    type: NONE
  hosts: 
    - "%"
  permissions:
    - database: "*"
      tables:
        - "*"
      privileges:
        - USAGE
        - SELECT
        - REPLICATION SLAVE
        - REPLICATION CLIENT
  ## Specify the cluster where the user is located.
  userOwner:
    clusterName: sample
    nameSpace: radondb
  ## Specify the secret object for user.
  secretSelector:
    secretName: sample-user-password
    secretKey: normalUser
