apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-studio-data
  namespace: sql-studio
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-studio-logs
  namespace: sql-studio
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce