apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sql-studio
  name: sql-studio
  namespace: sql-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-studio
  template:
    metadata:
      labels:
        app: sql-studio
    spec:
      # initContainers:
      #   - 
      containers:
        - image: docker.io/zengzhengrong889/sql-studio:1.0.2
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - /apps/usr/sqlstudio/linux/
                  - stop
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 18888
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: sql-studio
          ports:
            - containerPort: 18888
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 18888
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 4000Mi
              cpu: "1"
            requests:
              memory: 2000Mi
              cpu: "0.5"
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 18888
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /apps/usr/sqlstudio/data
              name: data
            - mountPath: /apps/usr/sqlstudio/log
              name: logs
            - mountPath: /apps/usr/sqlstudio/config/maicong.yaml
              name: sql-studio-config
              readOnly: true
              subPath: maicong.yaml
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: sql-studio-logs
        - name: data
          persistentVolumeClaim:
            claimName: sql-studio-data
        - configMap:
            defaultMode: 420
            items:
              - key: maicong.yaml
                path: maicong.yaml
            name: sql-studio
          name: sql-studio-config

---
kind: Service
apiVersion: v1
metadata:
  name: sql-studio
  namespace: sql-studio
spec:
  selector:
    app: sql-studio
  type: ClusterIP
  ports:
  - name: sql-studio
    port:  80
    targetPort: http

---
# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sql-studio
  namespace: sql-studio
spec:
  ingressClassName: nginx
  rules:
  - host: sql-studio.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sql-studio
            port:
              number: 80