# apiVersion: v1
# kind: Secret
# metadata:
#   labels:
#     common.k8s.elastic.co/type: elasticsearch
#     eck.k8s.elastic.co/credentials: "true"
#     eck.k8s.elastic.co/owner-kind: Elasticsearch
#     eck.k8s.elastic.co/owner-name: quickstart
#     eck.k8s.elastic.co/owner-namespace: eck-stack
#     elasticsearch.k8s.elastic.co/cluster-name: quickstart
#   name: quickstart-es-elastic-user
#   namespace: eck-stack
# type: Opaque
# data:
#   admin: YWRtaW4=
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: noauth
  namespace: eck-stack
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 8.4.3
  nodeSets:
    - config:
        node.store.allow_mmap: false
        xpack.security.enabled: false
        xpack.security.authc:
          anonymous:
            username: anonymous
            roles: superuser
            authz_exception: false
      count: 1
      name: default
      podTemplate:
        metadata:
          labels:
            app: noauth-elasticsearch
            maintainer: zengzhengrong
        spec:
          containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 3Gi
                cpu: 2
              requests:
                memory: 2Gi
                cpu: 1
            env:
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: openebs-hostpath
