apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: canal-admin
  namespace: canal
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
